apiVersion: skaffold/v2alpha3
kind: Config 
deploy: 
  kubectl:  
    manifests: 
      - ./infra/k8s/* 
build:
  local:
    push: false
  artifacts:    
    - image: christapherantony/server-1 
      context: server-1 
      docker:
        dockerfile: Dockerfile 
      sync:
        manual:
          - src: "**/*.js" 
            dest: .  
    - image: christapherantony/server-2
      context: server-2
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:  
          - src: '**/*.js'   
            dest: .

     